import { VehicleConfig, TrackConfig, QualityPreset, Controls, RaceSettings, Vector3 } from "@/types";

export type { Controls };

export const CAR_CONFIGS: VehicleConfig[] = [
  {
    id: "phantom-gt",
    name: "PHANTOM GT",
    model: "aventador.glb",
    description: "Aerodynamic masterpiece with razor-sharp design and a naturally aspirated V12. Built for speed and style.",
    color: "#ff1744",
    topSpeed: 350,
    acceleration: 9,
    handling: 7,
    braking: 8,
    nitro: 7,
    grip: 8,
    mass: 1575,
    enginePower: 770,
    gears: [3.91, 2.18, 1.47, 1.12, 0.91, 0.76],
    idleRpm: 800,
    maxRpm: 7500,
    gearRatios: [3.91, 2.18, 1.47, 1.12, 0.91, 0.76],
    finalDrive: 3.7,
    tireGrip: 0.95,
    aerodynamics: 0.35,
    driftModifier: 0.7,
  },
  {
    id: "rosso-corsa",
    name: "ROSSO CORSA",
    model: "f40.glb",
    description: "The iconic twin-turbo V8 supercar. Pure driving emotion with every fiber of its being.",
    color: "#ff0000",
    topSpeed: 330,
    acceleration: 8,
    handling: 9,
    braking: 9,
    nitro: 8,
    grip: 9,
    mass: 1100,
    enginePower: 490,
    gears: [3.23, 2.11, 1.46, 1.13, 0.92, 0.76],
    idleRpm: 1000,
    maxRpm: 8500,
    gearRatios: [3.23, 2.11, 1.46, 1.13, 0.92, 0.76],
    finalDrive: 3.5,
    tireGrip: 0.98,
    aerodynamics: 0.38,
    driftModifier: 0.65,
  },
  {
    id: "hyperion",
    name: "HYPERION",
    model: "mclaren-p1.glb",
    description: "Hybrid hypercar with Formula 1 DNA. Track-focused aerodynamics and lightning-fast acceleration.",
    color: "#ff00ff",
    topSpeed: 360,
    acceleration: 10,
    handling: 8,
    braking: 9,
    nitro: 9,
    grip: 9,
    mass: 1490,
    enginePower: 903,
    gears: [4.0, 2.4, 1.68, 1.24, 0.95, 0.73],
    idleRpm: 900,
    maxRpm: 8500,
    gearRatios: [4.0, 2.4, 1.68, 1.24, 0.95, 0.73],
    finalDrive: 3.8,
    tireGrip: 1.0,
    aerodynamics: 0.42,
    driftModifier: 0.6,
  },
  {
    id: "titan",
    name: "TITAN",
    model: "chiron.glb",
    description: "The absolute pinnacle of automotive engineering. Quad-turbo W16 power that defies physics.",
    color: "#00e676",
    topSpeed: 380,
    acceleration: 7,
    handling: 6,
    braking: 7,
    nitro: 6,
    grip: 8,
    mass: 1990,
    enginePower: 1578,
    gears: [3.0, 2.04, 1.31, 0.98, 0.78, 0.64],
    idleRpm: 700,
    maxRpm: 7000,
    gearRatios: [3.0, 2.04, 1.31, 0.98, 0.78, 0.64],
    finalDrive: 3.0,
    tireGrip: 0.92,
    aerodynamics: 0.4,
    driftModifier: 0.55,
  },
  {
    id: "apex-rsr",
    name: "APEX RSR",
    model: "porsche-gt3.glb",
    description: "Track-honed precision with naturally aspirated scream. Agility incarnate through every corner.",
    color: "#00b0ff",
    topSpeed: 320,
    acceleration: 7,
    handling: 10,
    braking: 10,
    nitro: 7,
    grip: 10,
    mass: 1495,
    enginePower: 520,
    gears: [3.88, 2.34, 1.63, 1.28, 1.04, 0.88],
    idleRpm: 1000,
    maxRpm: 9000,
    gearRatios: [3.88, 2.34, 1.63, 1.28, 1.04, 0.88],
    finalDrive: 3.91,
    tireGrip: 1.0,
    aerodynamics: 0.45,
    driftModifier: 0.7,
  },
  {
    id: "venom-x",
    name: "VENOM X",
    model: "agera.glb",
    description: "The ultimate analog hypercar. Raw, unfiltered speed with a twin-turbo V8 that screams.",
    color: "#ff4081",
    topSpeed: 400,
    acceleration: 9,
    handling: 5,
    braking: 6,
    nitro: 8,
    grip: 7,
    mass: 1400,
    enginePower: 1000,
    gears: [3.0, 2.11, 1.56, 1.24, 1.0, 0.82],
    idleRpm: 900,
    maxRpm: 8250,
    gearRatios: [3.0, 2.11, 1.56, 1.24, 1.0, 0.82],
    finalDrive: 3.2,
    tireGrip: 0.9,
    aerodynamics: 0.32,
    driftModifier: 0.6,
  },
];

export const CAR_CONFIG_MAP: Record<string, VehicleConfig> = CAR_CONFIGS.reduce(
  (acc, car) => {
    acc[car.id] = car;
    return acc;
  },
  {} as Record<string, VehicleConfig>
);

export const TRACK_CONFIGS: TrackConfig[] = [
  {
    id: "neon-tokyo",
    name: "NEON TOKYO",
    model: "neon-tokyo.glb",
    environment: "City",
    difficulty: "Hard",
    laps: 3,
    length: 4200,
    weather: "rain",
    timeOfDay: "night",
    thumbnail: "neon-tokyo.jpg",
    description: "Tight neon-lit corners through the heart of a futuristic city. Rain slicks the streets for maximum challenge.",
    checkpoints: [],
    startPositions: [],
  },
  {
    id: "dubai-highway",
    name: "DUBAI HIGHWAY",
    model: "dubai-highway.glb",
    environment: "Desert",
    difficulty: "Medium",
    laps: 3,
    length: 5800,
    weather: "clear",
    timeOfDay: "sunset",
    thumbnail: "dubai-highway.jpg",
    description: "Long sweeping straights and desert curves bathed in golden sunset light. Perfect for high-speed runs.",
    checkpoints: [],
    startPositions: [],
  },
  {
    id: "monaco-coast",
    name: "MONACO COAST",
    model: "monaco-coast.glb",
    environment: "Coastal",
    difficulty: "Expert",
    laps: 3,
    length: 3500,
    weather: "clear",
    timeOfDay: "day",
    thumbnail: "monaco-coast.jpg",
    description: "Mediterranean coastal circuit with elevation changes, tight tunnels, and sweeping ocean views.",
    checkpoints: [],
    startPositions: [],
  },
];

export const TRACK_CONFIG_MAP: Record<string, TrackConfig> = TRACK_CONFIGS.reduce(
  (acc, track) => {
    acc[track.id] = track;
    return acc;
  },
  {} as Record<string, TrackConfig>
);

export const GAME_CONSTANTS = {
  MAX_PLAYERS: 8,
  MIN_PLAYERS: 2,
  DEFAULT_LAPS: 3,
  NITRO_MAX: 100,
  NITRO_RECHARGE_RATE: 5,
  NITRO_CONSUMPTION_RATE: 20,
  NITRO_BOOST_MULTIPLIER: 1.5,
  DRIFT_SCORE_THRESHOLD: 0.3,
  DRIFT_POINTS_PER_SECOND: 100,
  COLLISION_DAMAGE_FACTOR: 0.1,
  RACE_TIMEOUT: 300,
  DISCONNECT_TIMEOUT: 30,
  NETWORK_TICK_RATE: 60,
  INTERPOLATION_BUFFER: 100,
  MAX_STEERING_ANGLE: 35,
  MIN_STEERING_ANGLE: 15,
  STEERING_SENSITIVITY: 0.8,
  FOV_MIN: 70,
  FOV_MAX: 85,
  FOV_SPEED_FACTOR: 0.15,
  DAMAGE_THRESHOLD_CRITICAL: 0.7,
  DAMAGE_THRESHOLD_MODERATE: 0.4,
} as const;

export const QUALITY_PRESETS: Record<QualityPreset, { shadows: boolean; antialias: boolean; postprocessing: boolean; particles: number; modelLOD: number; renderScale: number }> = {
  Ultra: { shadows: true, antialias: true, postprocessing: true, particles: 10000, modelLOD: 3, renderScale: 1.0 },
  High: { shadows: true, antialias: true, postprocessing: true, particles: 5000, modelLOD: 2, renderScale: 0.9 },
  Medium: { shadows: true, antialias: false, postprocessing: true, particles: 2000, modelLOD: 1, renderScale: 0.75 },
  Low: { shadows: false, antialias: false, postprocessing: false, particles: 500, modelLOD: 0, renderScale: 0.6 },
};

export const DEFAULT_CONTROLS: Controls = {
  forward: "ArrowUp",
  backward: "ArrowDown",
  left: "ArrowLeft",
  right: "ArrowRight",
  handbrake: "Space",
  nitro: "Shift",
  camera: "C",
  pause: "Escape",
};

export const DEFAULT_RACE_SETTINGS: RaceSettings = {
  trackId: "neon-tokyo",
  carId: "phantom-gt",
  laps: 3,
  weather: "clear",
  timeOfDay: "day",
  aiCount: 5,
  maxPlayers: 8,
};

export const COLORS = {
  primary: "#00f0ff",
  primaryLight: "#33ffff",
  primaryDark: "#00b8d9",
  secondary: "#ff00ff",
  secondaryLight: "#ff33ff",
  secondaryDark: "#cc00cc",
  accent: "#ff1744",
  accentLight: "#ff4081",
  background: "#0a0a0a",
  cardBg: "rgba(17, 17, 17, 0.7)",
  border: "rgba(255, 255, 255, 0.1)",
  textPrimary: "#f0f0f0",
  textSecondary: "#a0a0a0",
  textMuted: "#666666",
  neonBlue: "#00f0ff",
  neonPink: "#ff00ff",
  neonRed: "#ff1744",
  neonGreen: "#00e676",
  neonOrange: "#ff9100",
} as const;

export const ENGINE_SOUND_SPEEDS = [20, 40, 60, 80, 100, 120, 140, 160, 180, 200] as const;
export const AI_DIFFICULTY_LEVELS = ["easy", "medium", "hard"] as const;
export const CAMERA_MODES = ["chase", "cockpit", "cinematic"] as const;
export type CameraMode = (typeof CAMERA_MODES)[number];
